# -*- coding: utf-8 -*-

{
    'name': "3PL Warefor",

    'summary': """
        Managing 3PL System Of Warefor""",

    'description': """
    - Managing 3PL System Of Warefor.
    """,

    'author': "TechUltra Solutions Pvt. Ltd.",
    "support": "contact@techultrasolutions.com",
    'website': "https://www.techultrasolutions.com/",

    'category': 'Inventory/Purchase',
    "version": "16.4.64",
    'license': 'LGPL-3',
    'depends': ['delivery', 'purchase', 'mc_freight_app', 'warefor_crm', 'hr_timesheet', 'project',
                'advanced_many2many_tags', 'report_xlsx', 'web_map', 'delivery_tus', 'edi_3pl_tus',
                'user_warehouse_restriction'],

    'data': [
        'security/pallet_security.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/inventory_report_security.xml',
        'data/data.xml',
        'data/invoice_sequence.xml',
        'data/edi_environment_data.xml',
        'data/sale_confirmation_mail_temmplate.xml',
        'data/stages_data.xml',

        'report/po_report_templates.xml',
        'report/po_report.xml',
        'report/report_bill_of_lading.xml',

        'wizard/create_pallet_invoice_view.xml',
        'wizard/custom_invoice_wizard.xml',
        'wizard/transfer_inventory_wizard_view.xml',

        # 'views/assets.xml',
        'views/account_move_view.xml',
        'views/res_config_sets_extend_view.xml',
        'views/pallet_batch_view.xml',
        'views/product_3pl_box_view.xml',
        'views/pallet_box_items_view.xml',
        'views/stock_picking_view.xml',
        'views/stock_warehouse_views.xml',
        'views/product_views.xml',
        'views/product_box_configuration_view.xml',
        'views/product_qty_lines_view.xml',
        'views/pallet_import_cost_view.xml',
        'views/pallet_storage_cost_view.xml',
        'views/pallet_vas_cost_view.xml',
        'views/custom_invoice.xml',
        'views/pallet_box_line_view.xml',
        'views/pallet_product_line_view.xml',
        'views/purchase_views.xml',
        'views/res_partner_view.xml',
        'views/res_company_view.xml',
        'views/pallet_cost_config_view.xml',
        'views/freight_freight_views.xml',
        'views/freight_stage_views.xml',
        'views/edi_environment.xml',
        'views/racks_config.xml',
        'views/pallet_configuration.xml',
        'views/container_configuration.xml',
        'views/trailer_configuration.xml',
        'views/product_packaging.xml',
        'views/res_users_view.xml',
        'views/pallet_potd_view.xml',
        'views/custom_invoice_portal_templates.xml',
        'views/truck_driver_name_view.xml',
        'views/account_payment_view.xml',
        'views/freight_freight_osd_views.xml',
        'views/partner_available_quantity_view.xml',
        'views/osd_freight_transfer_line_view.xml',
        'views/warefor_internal_transfer_view.xml',
        'views/purchase_logistic_configuration_views.xml',
        'views/pallet_config_ibl_obl_views.xml',
        'wizard/freight_report_wizard_view.xml',
        'views/ibl_empty_full_report_views.xml',
        'views/hr_employee_view.xml',
        'report/report_action.xml',
        'report/pallet_label_template_view.xml',
        'report/pallet_label_views.xml',
        'report/report_location_barcode.xml',
        'report/report_purchase_order.xml',
        'report/empty_location.xml',
        'wizard/mass_pallet_movement_wizard.xml',
        'wizard/transfer_inventory_outbound_wizard_view.xml',
        'wizard/outbound_sign_view.xml',
        'data/mail_template_inherit_data_portal_welcome.xml',
        'report/pallet_shipping_label_template_view.xml',
        'report/pallet_shipping_label_views.xml',
        'report/logistic_pallet_label_template_view.xml',
        'report/custom_report_template.xml',
        'report/report_payment_details_template.xml',
        'wizard/truck_driver_signature_wizard_view.xml',
        'wizard/warehouse_manager_signature_wizard_view.xml',
        'wizard/osd_report_view_view.xml',
        'wizard/warehouse_container_report.xml',
        'report/bill_of_lading_template_view.xml',
        'report/freight_report_views.xml',
        'report/osd_report_template.xml',
        'report/report_credit_memo.xml',
        # 'wizard/empty_location_report.xml',
        'wizard/import_logistic.xml',
        'wizard/credit_memo_wizard_view.xml',
        'wizard/inbound_full_empty_container_wizard_views.xml',
        'wizard/delete_freight_freight.xml',
        'wizard/inventory_report_wizard_views.xml',
        'views/vendor_dba_views.xml',
        'wizard/carrier_pickup_dropoff_wizard_views.xml',
        'views/warehouse_user_training_view.xml',
        'views/stock_quant_views.xml',
        'views/freight_stage_data_view.xml',
        'views/fc_zipcode_table.xml',
    ],

    'qweb': [
        # "static/src/xml/kanaban_button.xml",
        "static/src/xml/form_button.xml",
        "static/src/components/chatter_extended.xml",
    ],
    'assets': {
        'web.assets_backend': [
            # 'warefor_3pl_tus/static/src/js/transfer_button.js',
            'warefor_3pl_tus/static/src/js/transfer_button_form.js',
            'warefor_3pl_tus/static/src/js/chatter_ext.js',
            'warefor_3pl_tus/static/src/css/style.css',
            'warefor_3pl_tus/static/src/xml/mail_chatter.xml',
            "warefor_3pl_tus/static/src/xml/list_button.xml",
            "warefor_3pl_tus/static/src/xml/forecasted_buttons.xml",
        ]
    },

    "images": [
        'static/description/banner.png',
    ],

    "external_dependencies": {
        "python": [],
        "bin": [],
    },
    'installable': True,
    'application': True,
}
