import base64
import csv
import io
import logging
import zipfile
from datetime import datetime, timedelta
from datetime import date
from io import StringIO

import requests
from odoo.exceptions import ValidationError

from odoo import models, fields
from odoo.tools.misc import split_every

_logger = logging.getLogger("walmart_logger_ept")


class WalmartOffer(models.Model):
    _name = 'walmart.offer.ept'
    _description = 'Walmart Offers'
    _rec_name = 'product_name'

    help_state_description = """
                PUBLISHED: The item is visible on Walmart.com and available for sale.
                READY_TO_PUBLISH: The item is in the final staging process and is ready to be published.
                IN_PROGRESS: The item is processing. An error could still occur at this point.
                UNPUBLISHED: The item has been made unavailable on Walmart.com because of backend 
                             rules, such as not having inventory for too long or problems with images.
                STAGE: The item is in the final staging process but has not been published 
                        because the Seller has not gone live.
                SYSTEM_PROBLEM: The item cannot be published. Contact Partner Support. """

    product_id = fields.Many2one('product.product', string="Odoo Product",
                                 help="Select Odoo Product")
    marketplace_id = fields.Many2one('walmart.marketplace.ept', string='Marketplace',
                                     help='Walmart Marketplace')
    walmart_sku = fields.Char('SKU', help="Walmart SKU")
    wpid = fields.Char('ProductId', help='An alphanumeric Product ID generated by Walmart')
    upc = fields.Char('UPC', help="The 12-digit bar code used extensively \
                      for retail packaging in the United States")
    gtin = fields.Char('GTIN', help='The GTIN-compatible Product ID (i.e. UPC or EAN). \
    UPCs must be 12 or 14 digitis in length. EANs must be 13 digits in length.')
    product_name = fields.Char(help='A seller-specified, alphanumeric \
    string uniquely identifying the product name.')
    product_category = fields.Many2one('walmart.product.type.ept', \
                                       help='A seller-specified, alphanumeric string uniquely \
                                   identifying the Product Type. Example: Diamond')
    state = fields.Selection([('PUBLISHED', 'PUBLISHED'), ('READY_TO_PUBLISH', 'READY_TO_PUBLISH'),
                              ('IN_PROGRESS', 'IN_PROGRESS'), ('UNPUBLISHED', 'UNPUBLISHED'),
                              ('STAGE', 'STAGE'), ('SYSTEM_PROBLEM', 'SYSTEM_PROBLEM')],
                             help=help_state_description)

    offer_fix_stock_type = fields.Selection([('fix', 'Fix'), ('percentage', 'Percentage')],
                                            string='Fix Stock Type')
    offer_fix_stock_value = fields.Float(string='Fix Stock Value',
                                         digits="Product UoS")
    fulfillment_by = fields.Selection([('Walmart Fulfilled','Walmart fulfillment'),('Seller Fulfilled',
                                                                                    'Seller Fulfillment'),
                                       ('WFS Eligible','WFS Eligible')],
                                      default='Seller Fulfilled')
    walmart_product_status_reason = fields.Char(string="Product Status Change Reason")
    walmart_product_lifecycle_status = fields.Selection(
        [('RETIRED', 'RETIRED'), ('ARCHIVED', 'ARCHIVED'), ('ACTIVE', 'ACTIVE')],
        string="Product Life Cycle")
    walmart_product_item_id = fields.Char(string="Item ID")
    walmart_product_offer_start_date = fields.Date(string="Product Start Date")
    walmart_product_offer_end_date = fields.Date(string="Product End Date")
    walmart_product_offer_creation_date = fields.Date(string="Product Creation Date")
    walmart_product_offer_last_update_date = fields.Date(string="Product Last Update Date")
    walmart_product_url = fields.Char(string="Product URL")
    walmart_product_review_count = fields.Integer(string="Product Reviews Count")
    walmart_product_avg_rating = fields.Float(string="Product Average Rating")
    exported_in_walmart = fields.Boolean()

    def process_offer_data(self, response, instance, log_book_id):
        """
        This method processes the data imported from Walmart and Syncs offers with Odoo Product.
        @author: Nikul Alagiya on Date 13/01/2022.
        """
        log_line_vals = []
        offer_data = response.get("ItemResponse", [])

        for data in offer_data:
            sku = data.get("sku")
            price = data.get("price", {})
            amount = price.get("amount", 0.0)
            name = data.get("productName", sku)

            _logger.info("Started processing the Offer: %s - %s" % (sku, name))

            offer_vals = self.prepare_offer_vals(data, instance)

            walmart_offer, odoo_product = self.search_walmart_offer_odoo_product(
                sku, instance)
            if walmart_offer:
                walmart_offer.write(offer_vals)
                _logger.info("Offer Updated: %s", name)
            elif odoo_product:
                offer_vals.update(
                    {"name": odoo_product.name, "product_id": odoo_product.id})
                walmart_offer = self.create(offer_vals)
                _logger.info("Offer Created: %s", name)
            else:
                self.env['common.log.lines.ept'].create_log_lines(
                    model_id=log_book_id.model_id.id,
                    res_id=False,
                    message="Offer not found",
                    default_code=sku,
                    log_book_id=log_book_id
                )
                continue
            if walmart_offer:
                pricelist_id = instance.pricelist_id
                if pricelist_id:
                    pricelist_id.set_product_price_ept(
                        walmart_offer.product_id.id, pricelist_id.id, amount)
            _logger.info("Processed the Offer: %s - %s" % (sku, name))

        return log_line_vals

    def export_stock_in_walmart(self, instance_id, walmart_products=False):
        """
        This method is used to Export Stock in Walmart.
        @param: Walmart Instance and Walmart Products List if Pass.
        @return: True
        @author: Nikul Alagiya on dated 19/01/2022
        """
        product_product_obj = self.env['product.product']
        walmart_instance_obj = self.env['walmart.marketplace.ept']
        walmart_log_line_obj = self.env['common.log.lines.ept']
        all_log_lines = []
        if not instance_id:
            instance_id = walmart_instance_obj.search([], order='id',limit=1)

        if not instance_id:
            log_line = walmart_log_line_obj.create_common_log_line_ept(
                message="Please, Select Walmart Marketplace to continue!", module='walmart_ept',
                res_id=False, walmart_marketplace_id=instance_id.id, model_name=self._name,
                log_line_type='fail', mismatch_details=True, operation_type="export")
            all_log_lines.append(log_line.id)
            return [], all_log_lines

        if walmart_products:
            odoo_products = walmart_products.mapped('product_id').ids
        else:
            last_update_date = instance_id.last_inventory_export_date or \
                               (datetime.now() - timedelta(30))
            odoo_products = product_product_obj.get_products_based_on_movement_date_ept(
                last_update_date, instance_id.company_id)
            walmart_products = self.search([
                ('product_id', '=', odoo_products), ('marketplace_id', '=', instance_id.id)])

        if not walmart_products:
            if odoo_products:
                log_line_type='fail'
                mismatch = True
                message = "There are no Walmart offers available, please import(sync) a Walmart offer first!"

            else:
                log_line_type = 'success'
                mismatch = False
                message = "Since the last export, no stock movements have been made !"
            log_line = walmart_log_line_obj.create_common_log_line_ept(
                message=message, module='walmart_ept', res_id=False, walmart_marketplace_id=instance_id.id,
                model_name=self._name, log_line_type=log_line_type, mismatch_details=mismatch, operation_type="export")
            all_log_lines.append(log_line.id)
            return [], all_log_lines

        inventory_list = self.prepare_inventory_list(instance_id, product_product_obj, odoo_products, walmart_products)
        feed_histories, log_lines = self.update_stock_in_walmart(inventory_list, instance_id)
        all_log_lines.extend(log_lines)
        instance_id.write({'last_inventory_export_date': datetime.now()})
        return feed_histories, all_log_lines

    def import_wfs_inventory(self, instance_id, auto_apply_adjustments):
        """
        This method is used to Import WFS Inventory in Walmart.
        :param instance_id: Walmart Instance
        :param auto_apply_adjustments: True or False
        :return: True
        """
        inventory_name = "Walmart%s_%s" % (instance_id.name, datetime.now().strftime("%d-%m-%Y"))
        products_stock = self.wfs_inventory_prepare_data_and_import_stock(instance_id)
        if products_stock:
            self.env['stock.quant'].create_inventory_adjustment_ept(products_stock,
                                                                    instance_id.wfs_warehouse_id.lot_stock_id,
                                                                    auto_apply_adjustments,
                                                                    inventory_name)
            instance_id.write({'last_wfs_inventory_import_date': datetime.now()})
            _logger.info("Going for the create inventory adjustment....")
        return True

    def wfs_inventory_prepare_data_and_import_stock(self, instance_id):
        """
        This method is used to prepare data and Import WFS Inventory in Walmart.
        :param instance_id: Walmart Instance
        :return: {}
        """
        walmart_offer_obj = self.env['walmart.offer.ept']
        products_stock = {}
        duplicate_walmart_product = []
        walmart_products = walmart_offer_obj.search([('exported_in_walmart', '=', True),
                                                     ('marketplace_id', '=', instance_id.id),
                                                     ('fulfillment_by', 'in', ['Walmart Fulfilled', 'WFS Eligible'])])
        # walmart_products = walmart_offer_obj.search([('marketplace_id', '=', instance_id.id)])
        sku = walmart_products.mapped('walmart_sku')
        for sku_chunk in split_every(1, sku):
            response = self.wfs_inventory_request_for_import_stock(sku_chunk, instance_id)
            if isinstance(response, str) or isinstance(response, list):
                continue
            products_stock, duplicate_walmart_product = self.prepare_wfs_inventory_data_for_inventory_adjustment(
                walmart_products, response, duplicate_walmart_product, products_stock)
            self._cr.commit()
        return products_stock

    def wfs_inventory_request_for_import_stock(self, sku_chunk, instance):
        """
        This method is used to call api and get response.
        :param sku_chunk: product sku
        :param instance: Walmart Instance
        :return: product response form walmart
        """
        log_line_obj = self.env['common.log.lines.ept']
        product_response = {}
        if instance.last_wfs_inventory_import_date:
            start_date = (instance.last_wfs_inventory_import_date - timedelta(days=1))
        else:
            today = date.today()
            start_date = (today - timedelta(days=30))
        try:
            walmart_conn_obj = instance.get_walmart_connection()
            str_sku = ",".join(sku_chunk)
            response = walmart_conn_obj.inventory.get_wfs_inventory(sku=str_sku)
            if not response:
                message = "Import WFS Inventory has not proper Response"
                _logger.info(message)
                log_line_obj.create_common_log_line_ept(message=message, model_name='walmart.offer.ept',
                                                        module='walmart_ept', operation_type='import', res_id=self.id)
            product_response = response
        except Exception as error:
            message = "Import WFS Inventory for products not perform"
            _logger.info(message)
            log_line_obj.create_common_log_line_ept(message=message, model_name='walmart.offer.ept',
                                                    module='walmart_ept', operation_type='import', res_id=self.id)
        return product_response

    def prepare_wfs_inventory_data_for_inventory_adjustment(self, walmart_products, response,
                                                            duplicate_walmart_product, products_stock):
        """
        This method is used to Prepare data for inventory adjustment.
        :param walmart_products: list of walmart products
        :param res_product: response of product
        :param duplicate_walmart_product: list of duplicate products
        :param products_stock: dict {}
        :return: dict {}
        """
        log_line_obj = self.env['common.log.lines.ept']
        qty = response.get('quantity', {}).get('amount')
        product = walmart_products.filtered(lambda x: x.walmart_sku == response.get('sku'))[0]
        if product.product_id.id not in duplicate_walmart_product:
            _logger.info("Adding qty for inventory adjustment of Walmart product: %s for ", product.product_id)
            products_stock.update({product.product_id.id: qty})
            duplicate_walmart_product.append(product.product_id.id)
        else:
            msg = "Duplicate product found in WooCommerce store with SKU: %s " % product.walmart_sku
            _logger.info(msg)
            log_line_obj.create_common_log_line_ept(message=msg, model_name='walmart.offer.ept',
                                                    default_code=product.walmart_sku,
                                                    module='walmart_ept', operation_type='import', res_id=self.id)
        return products_stock, duplicate_walmart_product

    def update_stock_in_walmart(self, inventory_list, instance_id):
        """
        This method is used to Export Stock in Walmart.
        @param: inventory_list and instance_id.
        @author: Nikul Alagiya on dated 19/01/2022
        """
        walmart_feed_history_obj = self.env['walmart.feed.history.ept']
        walmart_log_line_obj = self.env['common.log.lines.ept']
        walmart_conn_obj = instance_id.get_walmart_connection()
        feed_histories = []
        log_lines = []
        if inventory_list:
            try:
                response = walmart_conn_obj.inventory.bulk_update(items=inventory_list)
                if not response or not response.get('feedId', False):
                    message = 'Feed Submission id not found from Walmart Response...!'
                    log_line = walmart_log_line_obj.create_common_log_line_ept(
                        message=message, module='walmart_ept', model_name=self._name,
                        res_id=False, walmart_marketplace_id=instance_id.id,
                        log_line_type='fail', mismatch_details=True, operation_type="export")
                    log_lines.append(log_line.id)
                else:
                    feed_id = response.get("feedId", False)
                    if feed_id:
                        feed_history = walmart_feed_history_obj.create(
                            {'feed_id': feed_id, 'marketplace_id': instance_id.id})
                        feed_histories.append(feed_history)

            except Exception as err:
                raise ValidationError(str(err))
        return feed_histories, log_lines

    def prepare_inventory_list(self, instance_id, product_product_obj,
                               odoo_products, walmart_products=False):
        """
        This method is used to Prepare inventory list.
        @param:  instance_id, product_product_obj, odoo_products, walmart_products.
        @author: Nikul Alagiya on dated 19/01/2022
        """
        inventory_list = []
        product_stock_details = {}
        if instance_id.stock_field_id.name == 'free_qty':
            product_stock_details = product_product_obj.get_free_qty_ept(instance_id.warehouse_id, odoo_products)
        elif instance_id.stock_field_id.name == 'virtual_available':
            product_stock_details = product_product_obj.get_forecasted_qty_ept(instance_id.warehouse_id, odoo_products)
        elif instance_id.stock_field_id.name == 'qty_available':
            product_stock_details = product_product_obj.get_onhand_qty_ept(instance_id.warehouse_id, odoo_products)

        if not product_stock_details:
            return False

        for item in walmart_products:
            walmart_product_stock = product_stock_details.get(
                item.product_id.id, 0.0)
            stock = self.stock_calculation_ept(walmart_product_stock, item.offer_fix_stock_type,
                                               item.offer_fix_stock_value)

            inventory_list += [{"sku": item.walmart_sku, "quantity": str(stock)}]

        return inventory_list

    def stock_calculation_ept(self, actual_stock, fix_stock_type=False, fix_stock_value=0):
        """
        This method relocates calculate stock.
        :param actual_stock: This arguments relocates actual stock.
        :param fix_stock_type: This arguments relocates type of stock type.
        :param fix_stock_value: This arguments relocates value of stock value.
        :return: actual_stock
        """
        if actual_stock >= 1.00:
            if fix_stock_type == 'fix':
                if fix_stock_value >= actual_stock:
                    return actual_stock
                else:
                    return fix_stock_value

            elif fix_stock_type == 'percentage':
                quantity = int((actual_stock * fix_stock_value) / 100.0)
                if quantity >= actual_stock:
                    return actual_stock
                else:
                    return quantity
        return actual_stock

    def export_price_in_walmart(self, instance_id, walmart_products=False):
        """
        This method is used to Export Product Price in Walmart.
        @param: Walmart Instance and Walmart Products List in Pass .
        @return: True
        """
        walmart_log_line_obj = self.env['common.log.lines.ept']
        walmart_instance_obj = self.env['walmart.marketplace.ept']
        all_log_lines = []
        all_feed_histories = []

        if not instance_id:
            instance_id = walmart_instance_obj.search([('state', '=', 'confirmed')], limit=1)

        if not instance_id:
            log_line_id = walmart_log_line_obj.create_common_log_line_ept(
                message='Please, Select Walmart Marketplace to continue!',
                module='walmart_ept', res_id=False, walmart_marketplace_id=instance_id.id,
                model_name=self._name, log_line_type='fail', mismatch_details=True,
                operation_type="export")
            return [], [log_line_id.id]

        if not walmart_products:
            walmart_products = self.search([('marketplace_id', '=', instance_id.id)])

        if not walmart_products:

            log_line_id = walmart_log_line_obj.create_common_log_line_ept(
                message="There are no Walmart offers available, please import(sync) a Walmart offer first!",
                module='walmart_ept', res_id=False, walmart_marketplace_id=instance_id.id,
                model_name=self._name, log_line_type='fail', mismatch_details=True,
                operation_type="export")
            return [], [log_line_id.id]

        feed_histories, log_lines = self.prepare_updated_price_list_and_update_in_walmart(instance_id, walmart_products,
                                                              walmart_log_line_obj)
        all_log_lines.extend(log_lines)
        all_feed_histories.extend(feed_histories)
        return all_feed_histories, all_log_lines

    def prepare_updated_price_list_and_update_in_walmart(self, instance_id, walmart_products,
                                                         walmart_log_line_obj):
        """
        This method is used to Prepare Product Price List and Update in Walmart.
        @param: Walmart Instance and Walmart Products List in Pass .
        @return: True
        """
        updated_price_list = []
        price_list = instance_id and instance_id.pricelist_id
        log_lines = []
        feed_histories = []

        for wprod in range(0, len(walmart_products), 2):
            products = walmart_products[wprod:wprod + 2]

            for walmart_product_id in products:
                product_price = price_list._get_product_price(walmart_product_id.product_id, 1.0)
                updated_price_list += [
                    {"sku": walmart_product_id.walmart_sku,
                     "currentCurrency": price_list.currency_id.name,
                     "currentPrice": str(product_price),
                     }]
            feed_history, log_line = self.update_prices_in_walmart(instance_id, updated_price_list, walmart_log_line_obj)
            log_lines.append(log_line)
            feed_histories.append(feed_history)
        return feed_histories, log_lines

    def update_prices_in_walmart(self, instance_id, updated_price_list, walmart_log_line_obj):
        """
        This method is used to Update price in Walmart.
        @param: Walmart Instance and Walmart Products List in Pass .
        @return: True
        """
        walmart_feed_history_obj = self.env['walmart.feed.history.ept']
        walmart_conn_obj = instance_id.get_walmart_connection()
        log_line_id = False
        feed_history_id = False
        if updated_price_list:
            try:
                response = walmart_conn_obj.prices.bulk_update(items=updated_price_list)
                if not response or not response.get('feedId', False):
                    log_line_id = walmart_log_line_obj.create_common_log_line_ept(
                        message='Feed Submission id not found from Walmart Response while exporting price...!',
                        module='walmart_ept', res_id=False, walmart_marketplace_id=instance_id.id,
                        model_name=self._name, log_line_type='fail', mismatch_details=False,
                        operation_type="export")
                    log_line_id = log_line_id.id
                else:
                    feed_id = response.get('feedId', '').strip()
                    _logger.info(response)
                    if feed_id:
                        feed_history_id = walmart_feed_history_obj.create(
                            {'feed_id': feed_id, 'marketplace_id': instance_id.id})
                        feed_history_id = feed_history_id.id

            except Exception as err:
                raise ValidationError(str(err))
        return feed_history_id, log_line_id

    # FIXME: We are not supporting any deleteing operation at this moment
    def walmart_retire_products_ept(self):
        """This method is used to Retire Product (Expire) in Walmart.
                @param Walmart Instance and Walmart Products List in Pass .
                @return: True

        """
        return True

    # def walmart_get_item_report_ept(self, instance_id, update_image=False,
    #                                 inventory_adjustments=False,
    #                                 location_id=False):
    #     """
    #     This method is used to Get Report Item(Product) And
    #     Full fulfilment Other Product Details in Odoo.
    #     @param
    #         Walmart Instance
    #         Update Image
    #         Update Inventory
    #         Inventory Location
    #     @return: True
    #     """
    #
    #     def get_return_date(date):
    #         """
    #         Fetch to formatted date.
    #         :param date:
    #         :return: formatted date.
    #         """
    #         return datetime.strptime(date.replace('/', '-'), '%m-%d-%Y').date() if date else ''
    #
    #     walmart_log_book_obj = self.env['common.log.book.ept']
    #     walmart_log_line_obj = self.env['common.log.lines.ept']
    #
    #     stock_inventory_obj = self.env['stock.inventory']
    #     product_pricelist_item_obj = self.env['product.pricelist.item']
    #
    #     inventorty_adjustments_list = []
    #
    #     walmart_conn_obj = instance_id.get_walmart_connection()
    #
    #     model_id = walmart_log_line_obj.get_model_id(self._name)
    #     log_book_id = walmart_log_book_obj.create_common_log_book(
    #         model_id=model_id, module='walmart_ept', process_type='import',
    #         instance_field='walmart_marketplace_id', instance=instance_id)
    #     try:
    #         response = walmart_conn_obj.report.all()
    #         if not response:
    #             message = 'Item Report not found from Walmart...!'
    #             walmart_log_line_obj.create_log_lines(
    #                 model_id=model_id, log_book_id=log_book_id, res_id=False, message=message)
    #         else:
    #             path = "/tmp"
    #             z = zipfile.ZipFile(io.BytesIO(response))
    #             z.extractall(path=path)
    #             for filename in z.namelist():
    #                 fh = open('/tmp/%s' % filename, 'rb')
    #                 csvf = StringIO(fh.read().decode())
    #                 item_reports_data = csv.DictReader(csvf, delimiter=',')
    #                 rows = list(item_reports_data)
    #                 total_rows = len(rows)
    #                 fh.close()
    #                 for count, item_report in enumerate(rows, start=1):
    #                     walmart_product_sku = item_report.get('SKU', '').strip()
    #                     _logger.info("Processing item report product:{} row {} out of {}".format(
    #                         walmart_product_sku, count, total_rows))
    #                     walmart_product_id = walmart_product_sku and self.search(
    #                         [('walmart_sku', '=', walmart_product_sku),
    #                          ('marketplace_id', '=', instance_id.id)], limit=1)
    #                     if not walmart_product_id:
    #                         _logger.info(
    #                             "Walmart product not found with SKU:{} at row number:{}".format(
    #                                 walmart_product_sku, count
    #                             ))
    #                         continue
    #                     status_reason = item_report.get(
    #                         "STATUS CHANGE REASON", '').strip()
    #                     lifecycle_status = item_report.get(
    #                         "LIFECYCLE STATUS", '').strip()
    #                     walmart_product_item_id = item_report.get("ITEM ID", '').strip()
    #                     offer_start_date = get_return_date(
    #                         item_report.get("OFFER START DATE", '').strip())
    #                     offer_end_date = get_return_date(
    #                         item_report.get("OFFER END DATE", '').strip())
    #                     offer_creation_date = get_return_date(
    #                         item_report.get("ITEM CREATION DATE", '').strip())
    #                     offer_last_update_date = get_return_date(
    #                         item_report.get("ITEM LAST UPDATED", '').strip())
    #                     walmart_product_url = item_report.get("ITEM PAGE URL", '').strip()
    #                     review_count = item_report.get(
    #                         "REVIEWS COUNT", '').strip()
    #                     avg_rating = item_report.get(
    #                         "AVERAGE RATING", '').strip()
    #                     walmart_product_price = item_report.get("PRICE", '').strip()
    #
    #                     walmart_product_id.write(
    #                         {"walmart_product_status_reason": status_reason,
    #                          "walmart_product_lifecycle_status": lifecycle_status,
    #                          "walmart_product_item_id": walmart_product_item_id,
    #                          "walmart_product_offer_start_date": offer_start_date,
    #                          "walmart_product_offer_end_date": offer_end_date,
    #                          "walmart_product_offer_creation_date": offer_creation_date,
    #                          "walmart_product_offer_last_update_date": offer_last_update_date,
    #                          "walmart_product_url": walmart_product_url,
    #                          "walmart_product_review_count": review_count,
    #                          "walmart_product_avg_rating": avg_rating})
    #                     odoo_product = walmart_product_id.product_id or False
    #                     if walmart_product_price and odoo_product:
    #                         price = float(walmart_product_price)
    #                         price_list_item_id = instance_id.pricelist_id.item_ids.filtered(
    #                             lambda item: item.product_tmpl_id.id == odoo_product.product_tmpl_id.id)
    #                         if price_list_item_id:
    #                             price_list_item_id.write({"fixed_price": price})
    #                         else:
    #                             item_price_vals = {
    #                                 "applied_on": "1_product",
    #                                 "product_tmpl_id": odoo_product.product_tmpl_id.id,
    #                                 "compute_price": "fixed",
    #                                 "min_quantity": 1,
    #                                 "fixed_price": price,
    #                                 "pricelist_id": instance_id.pricelist_id.id or False}
    #                             product_pricelist_item_obj.create(item_price_vals)
    #
    #                     if update_image:
    #                         walmart_product_image_url = item_report.get(
    #                             "PRIMARY IMAGE URL", '').strip()
    #                         try:
    #                             filename = requests.get(
    #                                 walmart_product_image_url, stream=True,
    #                                 verify=False, timeout=10)
    #                             img = base64.b64encode(filename.content)
    #                             walmart_product_id.product_id.write({"image_1920": img})
    #                         except Exception as err:
    #                             _logger.exception(
    #                                 "Got an exception while fetching image {}".format(err))
    #
    #                     if inventory_adjustments:
    #                         product_inv = item_report.get("INVENTORY COUNT", '').strip()
    #                         if product_inv:
    #                             inventorty_adjustments_list.append(
    #                                 {
    #                                     "product_id": walmart_product_id.product_id,
    #                                     "qty": int(product_inv)
    #                                 }
    #                             )
    #
    #         if inventorty_adjustments_list:
    #             sequence = self.env.ref(
    #                 'walmart_ept.ir_sequence_inventory_inventory_adjustments_ept')
    #             if sequence:
    #                 record_name = sequence.next_by_id()
    #             else:
    #                 record_name = '/'
    #
    #             line_ids = []
    #             for inventory_adjustments_line in inventorty_adjustments_list:
    #                 product = inventory_adjustments_line.get("product_id")
    #                 qty = inventory_adjustments_line.get("qty")
    #                 if product and qty != 0:
    #                     line_vals = {'location_id': location_id and location_id.id,
    #                                  'product_id': product.id,
    #                                  'product_uom_id': product.uom_id.id,
    #                                  'product_qty': qty}
    #                     line_ids.append((0, 0, line_vals))
    #
    #             vals = {'name': record_name,
    #                     'location_ids': [(6, 0, location_id.ids)],
    #                     'line_ids': line_ids
    #                     }
    #             stock_inventory_obj.create(vals)
    #
    #     except Exception as error:
    #         _logger.exception(error)
    #         raise ValidationError(str(error))
    #
    #     return True

    def prepare_offer_vals(self, data, instance):
        """
        This method  prepares vals to create a offer from data.
        """
        product_type_id = self.env['walmart.product.type.ept']
        product_type = data.get("productType") and data.get("productType").strip()
        if product_type:
            product_type_id = product_type_id.search([('name', '=ilike', product_type)])
            if not product_type_id:
                product_type_id = product_type_id.create({'name': product_type})
        return {"walmart_sku": data.get("sku"),
                "product_category": product_type_id.id,
                "marketplace_id": instance.id,
                "gtin": data.get("gtin", ""),
                "wpid": data.get("wpid", ""),
                "upc": data.get("upc", ""),
                "product_name": data.get("productName"),
                "fulfillment_by": data.get('Fulfillment Type'),
                "state": data.get('publishedStatus'),
                "walmart_product_lifecycle_status": data.get('lifecycleStatus'),
                "exported_in_walmart": True
                }

    def search_walmart_offer_odoo_product(self, sku, instance):
        """
        This method searches for the Walmart offer first,
        if offer not found than searches for the Odoo product.
        """
        odoo_product = self.env["product.product"]
        walmart_offer = self.search([("walmart_sku", "=", sku),
                                     ("marketplace_id", "=", instance.id)], limit=1)
        if not walmart_offer:
            odoo_product = odoo_product.search([("default_code", "=", sku)], limit=1)
        else:
            odoo_product = walmart_offer.product_id
        return walmart_offer, odoo_product
