# -*- coding: utf-8 -*-
{
    'name': "Sales Dashboard Ninja",

    'summary': """
    Sales Dashboard Ninja!
    """,

    'description': """
        Dashboard Ninja v11.0,
        Odoo Dashboard, 
        Dashboard,
        Odoo apps,
        Dashboard app,
        HR Dashboard,
        Sales Dashboard, 
        inventory Dashboard, 
        Lead Dashboard, 
        Opportunity Dashboard, 
        CRM Dashboard,
        POS,
        POS Dashboard,
        Connectors,
        Web Dynamic,
        Report Import/Export,
        Date Filter,
        HR,
        Sales,
        Theme,
        Tile Dashboard,
        Dashboard Widgets,
        Dashboard Manager,
        Debranding,
        Customize Dashboard,
        Graph Dashboard,
        Charts Dashboard,
        Invoice Dashboard,
        Project management,
        ksolves,
        ksolves apps,
        ksolves india pvt. ltd.,
        Sales Dashboards,
        Best Sales Dashboards,
        Sale Orders,
        Customer Dashboard,
        Partners Dashboard,
        Top Customers Dashboard,
        Invoice Dashboard,
        V12 Dashboard,
        Dashboard v12.0,
        Odoo Dashboard v12.0,
        Sales Dashboard v12.0,
        Odoo Sales Dashboards,
        Best Sales Dashboard Apps,
        Best Dashboard Apps,
        Best Odoo Apps,
        Dashboard For Sales,
        Odoo Dashboard apps,
        Best Odoo Dashboard Apps,
        Dashboard apps,
        Dashboards for Sales,
        HR Dashboard Apps,
        Sales Dashboard Apps, 
        inventory Dashboard Apps, 
        Lead Dashboards, 
        Opportunity Dashboards,
        CRM Dashboards,
        Best POS Apps,
        POS Dashboards,
        Sales Connectors,
        Web Dynamic Apps,
        Report Import/Export,
        Date Filter Apps,	
        Tile Dashboard Apps,
        Dashboard Widgets,
        Dashboard Manager Apps,
        Debranding Apps,
        Customize Dashboard Apps
        Graph Dashboard Apps,
        Charts Dashboard Apps,
        Invoice Dashboard Apps,
        Project management Apps
        dashboard, 
        odoo dashboard, 
        odoo sales apps, 
        all in one sales dashboard, 
        sales dashboard odoo, 
        dashboard items, 
        sales multiple dashboards, 
        sales dashboard menu, 
        dashboard view, 
        create multiple dashboards, 
        multiple dashboard menu, 
        edit dashboard items, 
        sales dahsboard view, 
    """,
    'author': "Ksolves India Pvt. Ltd.",
    'license': 'OPL-1',
    'currency': 'EUR',
    'price': 0.0,
    'website': "https://www.ksolves.com",
    'maintainer': 'Ksolves India Pvt. Ltd.',
    'category': 'Tools',
    'support': 'sales@ksolves.com',
    'live_test_url': 'https://dashboardninja12.kappso.com/web/demo_login',
    'images': ['static/description/banner.png'],

    'depends': ['ks_dashboard_ninja', 'sale', 'sale_management'],

    'data': [
        'data/ks_sales_data.xml',
    ],

}
