# -*- coding: utf-8 -*-

from . import truck_driver_name
from . import stock_location_place
from . import res_config_sets_extend
from . import pallet_batch_tus
from . import product_3pl_box_tus
from . import pallet_box_items
from . import freight_frieght
from . import stock_picking
from . import stock_warehouse
from . import product
from . import product_box_configuration
from . import pallet_import_cost
from . import pallet_storage_cost
from . import pallet_vas_cost
from . import account_move
from . import res_company_extend
from . import account_payment
from . import pallet_box_lines
from . import pallet_product_lines
from . import purchase_order
from . import stock_move
from . import vendor_dba
from . import res_partner
from . import pallet_cost_config
from . import custom_invoice
from . import edi_environment
from . import racks_config
from . import pallet_configuration
from . import container_configuration
from . import trailer_configuration
from . import freight_package_lines
from . import pallet_fob_cost
from . import res_users
from . import product_packaging
from . import uom_category
from . import osd_report
from . import partner_available_quantity
from . import osd_frieght_transfer_line
from . import warefor_internal_transfer
from . import pallet_config_obl_ibl
from . import storage_type_ibl
from . import ibl_empty_full_report
from . import stock_rule
from . import hr_employee
from . import mail_message
from . import warehouse_user_training
from . import freight_stages_data
from . import FCZipCodeTable
from . import freight_claims
