from . import project_task
from . import ibl_limited_access
from . import base
from . import stock_quant
from . import storage_type_ibl
from . import freight_freight_ibl
from . import mail_notification
from . import freight_order_line
from . import osd_freight_transfer_line
from . import res_users
from . import product_template
from . import product_product
