{
    # Theme information

    'name': 'Theme Clarico Vega',
    'category': 'Theme/eCommerce',
    'summary': 'An Odoo eCommerce Solution with a lot of well-analized features. Suitable for all kind of eCommerce Businesses like Furniture, Fashion, Electronics, Beauty, Fitness, Jewelry, etc.',
    'version': '16.2.3',
    'license': 'OPL-1',
    'depends': [
        'emipro_theme_base','website_mass_mailing'
    ],
    'data': [
        'templates/mega_menu.xml',
        'templates/wishlist.xml',
        'templates/shop.xml',
        'templates/product.xml',
        'templates/login_popup.xml',
        'templates/compare.xml',
        'templates/odoo_default_buttons_style.xml',
        'templates/product_label.xml',
        'templates/portal.xml',
        'templates/quick_view.xml',
        'templates/assets_pwa.xml',
        'templates/emipro_snippets_settings.xml',
        'templates/theme_customise_option.xml',
        'templates/header.xml',
        'templates/footer.xml',
        'templates/cart.xml',
        'templates/product_snippet_template_data.xml',
        'templates/brand.xml',
        'templates/snippets_style.xml',
        'templates/emipro_custom_snippets.xml',
        'templates/odoo_default_snippets.xml',
        'templates/blog.xml',
    ],
    'assets': {
        'web._assets_frontend_helpers': [
            'theme_clarico_vega/static/lib/theme/para_size.scss',
            'theme_clarico_vega/static/lib/theme/variables.scss',
            'theme_clarico_vega/static/lib/theme/button.scss',
            'theme_clarico_vega/static/lib/theme/heading_size.scss',
            'theme_clarico_vega/static/lib/theme/link_color.scss',
        ],
        'web._assets_primary_variables': [
            'theme_clarico_vega/static/src/scss/theme_color.scss',
            'theme_clarico_vega/static/src/scss/customise_variables.scss',
        ],
        'web.assets_frontend': [
            'theme_clarico_vega/static/src/scss/blog.scss',
            'theme_clarico_vega/static/src/scss/wishlist.scss',
            'theme_clarico_vega/static/src/scss/mixins.scss',
            'theme_clarico_vega/static/src/scss/style_1.scss',
            'theme_clarico_vega/static/src/scss/style_2.scss',
            'theme_clarico_vega/static/src/scss/style_3.scss',
            'theme_clarico_vega/static/src/scss/owl.carousel.min.css',
            'theme_clarico_vega/static/src/scss/style_4.scss',
            'theme_clarico_vega/static/src/scss/megamenu.scss',
            'theme_clarico_vega/static/src/scss/product_slider.scss',
            'theme_clarico_vega/static/src/scss/portal.scss',
            'theme_clarico_vega/static/src/scss/shop.scss',
            "theme_clarico_vega/static/src/scss/snippets.scss",
            'theme_clarico_vega/static/src/scss/button/animation.scss',
            'theme_clarico_vega/static/src/scss/login_popup.scss',
            'theme_clarico_vega/static/src/scss/label/sale_label.scss',
            'theme_clarico_vega/static/src/js/frontend/owl.carousel.js',
            'theme_clarico_vega/static/src/js/frontend/login_popup.js',
            'theme_clarico_vega/static/src/js/frontend/mixins.js',
            'theme_clarico_vega/static/src/js/frontend/theme_script.js',
            'theme_clarico_vega/static/src/js/frontend/dynamic_menu.js',
            'emipro_theme_base/static/src/js/frontend/quick_view.js',
            'theme_clarico_vega/static/src/scss/header.scss',
            'theme_clarico_vega/static/src/scss/footer.scss',
            'theme_clarico_vega/static/src/js/frontend/cart_popup.js',
            'theme_clarico_vega/static/src/xml/search.xml',
        ],
        'website.assets_wysiwyg': [
            'theme_clarico_vega/static/src/js/editor/snippets.editor.js',
            'theme_clarico_vega/static/src/js/editor/website_sale_editor.js',
        ],
        'web_editor.assets_wysiwyg': [
            'theme_clarico_vega/static/src/js/editor/snippet.options.js',
        ],
    },
    # Author
    'author': 'Emipro Technologies Pvt. Ltd.',
    'website': 'https://www.emiprotechnologies.com',
    'maintainer': 'Emipro Technologies Pvt. Ltd.',
    'live_test_url': 'https://claricovega.theme16.demo.emiprotechnologies.com/',
    'images': [
        'static/description/main_poster.jpg',
        'static/description/main_screenshot.gif',
    ],

    # Technical
    'installable': True,
    'auto_install': False,
    'price': 229.00,
    'currency': 'USD',
}
