{
    'name': 'ShipStation Odoo Connector',
    'version': '16.0.1.8',
    'category': 'Sales',
    'license': 'OPL-1',
    'summary': 'Integrate & Manage all your Shipstation account operations from Odoo.With Emipro’s Shipstation Odoo integrations, you can manage your shipping operations easily and efficiently from Odoo, no matter how big or small your business is. Offer your customers more choices with numerous options for shipping.Customers can manage shipping labels, various shipping methods, shipping carrier management, importing unshipped orders from Odoo and then update the information in Odoo for the shipped orders.Emipro is also having integration for well known ecommerce solutions or applications named as Woocommerce connector , Shopify connector , magento connector and also we have solutions for Marketplace Integration such as Odoo Amazon connector , Odoo eBay connector , Odoo walmart Connector , Odoo Bol.com connector.For the customers who are into Dropship business, we do provide EDI Integration that can help them manage their Dropshipping business with our Dropshipping integration or Dropshipper integration It is listed as Dropshipping EDI integration and Dropshipper EDI integration.Emipro applications can be searched with different keywords like Amazon integration , Shopify integration , Woocommerce integration, Magento integration , Amazon vendor center module , Amazon seller center module , Inter company transfer , eBay integration , Bol.com integration , inventory management , warehouse transfer module , dropship and dropshipper integration and other Odoo integration application or module',
    'depends': ['delivery', 'stock_picking_batch', 'common_connector_library'],
    'data': [
        'security/shipstation_security.xml',
        'security/ir.model.access.csv',
        'view/view_shipstationinstance_ept.xml',
        'wizard/res_config_view.xml',
        'wizard/shipstation_process_import_export_view.xml',
        'data/product_data.xml',
        'data/ir_cron_view.xml',
        'data/shipment_tracking_mail_template.xml',
        'view/cancel_shipment_server_action.xml',
        'view/crm_team_view.xml',
        'view/sale_order_view.xml',
        'view/shipstation_marketplace_view.xml',
        'view/shipstation_store_view.xml',
        'view/shipstation_carrier_view.xml',
        'view/shipstation_services_ept_view.xml',
        'view/shipstation_warehouse_view.xml',
        'view/shipstation_product_view.xml',
        'view/deliver_carrier_view.xml',
        'view/form_view_stock_package_type.xml',
        'view/stock_picking_view.xml',
        'view/common_log.xml',
        'view/product.xml',
        'wizard/shipstation_cron_configuration_ept_view.xml',
        'view/shipstation_weight_mapping_view.xml',
        'view/common_log_lines_ept.xml',
        'view/view_stock_package_type.xml',
        'view/stock_picking_batch_view.xml',
        'view/generate_multiple_label_action.xml',
    ],
    'images': ['static/description/ShipStation.jpg'],
    # Author
    'author': 'Emipro Technologies Pvt. Ltd.',
    'website': 'http://www.emiprotechnologies.com',
    'maintainer': 'Emipro Technologies Pvt. Ltd.',
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'live_test_url': 'https://www.emiprotechnologies.com/r/cpf',
    'price': '79',
    'currency': 'EUR',
}
