# -*- coding: utf-8 -*-
{
    'name': "Inventory Dashboard Ninja",

    'summary': """
    Inventory Dashboard Ninja!
    """,

    'description': """
        Dashboard Ninja v12.0,
        Odoo Dashboard, 
        Dashboard,
        Odoo apps,
        Dashboard app,
        HR Dashboard,
        Sales Dashboard, 
        inventory Dashboard, 
        Lead Dashboard, 
        Opportunity Dashboard, 
        CRM Dashboard,
	    POS,
	    POS Dashboard,
	    Connectors,
	    Web Dynamic,
	    Report Import/Export,
	    Date Filter,
	    HR,
	    Sales,
	    Theme,
	    Tile Dashboard,
	    Dashboard Widgets,
	    Dashboard Manager,
	    Debranding,
	    Customize Dashboard,
	    Graph Dashboard,
	    Charts Dashboard,
	    Invoice Dashboard,
	    Project management,
        ksolves,
        ksolves apps,
        ksolves india pvt. ltd.,
        Best Inventory Dashboard Apps,
        Inventory Dashboard Apps,
        Stock Inventory Dashboard Apps,
        Best Warehouse Management Dashboard Apps,
        Warehouse Management Dashboard Apps,
        Warehouse Dashboard Apps,
        Stock  Management Dashboard Apps,
        Best Stock Management Dashboard Apps,
        Dashboards,
        Product Dashboards,
        Inventory Management System,
        Stock management System,
        Purchase Order Dashboards,
        Sales Order Dashboards,
        Stock Alert Apps,
        Inventory Alert Apps,
        Product Dashboard,
        Expiry Alert Apps,
        Alert Expiry Apps,
        Sales Dashboard,
        Best Dashboard Apps,
        Inventory Age Report,
        Inventory Report, 
        Inventory Valuation,
        Inventory Quantities,
        Stock per Location,
        Top selling items Dashboard,
        Odoo Dashboard,
        Dashboard for Odoo,
        Inventory Tracker Apps,
        Inventory Tracking Apps,
        Stock Tracker Apps,
        Warehouse Tracker Apps
    """,

    'author': "Ksolves India Pvt. Ltd.",
    'license': 'OPL-1',
    'currency': 'EUR',
    'price': 0.0,
    'website': "https://www.ksolves.com",
    'live_test_url': 'https://dashboardninja12.kappso.com/web/demo_login',
    'maintainer': 'Ksolves India Pvt. Ltd.',
    'category': 'Tools',
    'support': 'sales@ksolves.com',
    'version': '1.0.0',
    'images': ['static/description/banner.png'],

    'depends': ['ks_dashboard_ninja', 'stock', 'product_expiry'],

    'data': [
        'security/ir.model.access.csv',
        'data/ks_inventory_data.xml',

    ],

}
